name: Build Extension

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: yarn

      - name: Build project
        run: yarn run build

    #   - name: Archive build artifacts
    #     uses: actions/upload-artifact@v2
    #     with:
    #       name: extension
    #       path: path/to/build/directory
